import Joi from "joi";
/**
 * @openapi
 * components:
 *   schemas:
 *     User:
 *       type: object
 *       required:
 *         - name
 *         - date
 *         - capacity
 *         - registrationCount
 *         - status
 *         - category
 *         -createdAt
 *         - updatedAt
 *      properties:
 *        id:
 *         type: string
 *         description: Unique identifier for the user account
 *         example: "123e4567-e89b-12d3-a456-426614174000"
 *       name:
 *        type: string
 *        minLength: 3
 *        maxLength: 100
 *        description: The name of the user account
 *        example: "John Doe"
 *      date:
 *        type: string
 *        format: date
 *        description: The date of the event
 *        example: "2024-01-15"
 *      capacity:
 *        type: integer
 *        minimum: 5
 *        description: The maximum number of attendees for the event
 *        example: 50
*     registrationCount:
*         type: integer
*         minimum: 0
*         description: The current number of registered attendees for the event
*         example: 25
*     status:
*        type: string
*        enum: [active, cancelled, completed]
*        description: The current status of the event
*        example: "active"
*     category:
*        type: string
*        enum: [general, conference, workshop, meetup]
*        description: The category of the event
*        example: "conference"
*     createdAt:
*        type: string
*        format: date-time
*        description: When the user account was created
*        example: "2024-01-15T10:30:00Z"
*      updatedAt:
*        type: string
*        format: date-time
*        description: When the user account was last updated
*        example: "2024-01-20T14:45:00Z"
*/
export const postSchemas = {
  // POST /events - Create new event

  create: {
    body: Joi.object({
      // id is generated by the server, so client should NOT send it
      id: Joi.forbidden().messages({
        "any.unknown": "ID cannot be provided on create",
      }),

      name: Joi.string()
        .min(3)
        .max(100)
        .required()
        .messages({
          "string.base": "\"name\" must be a string",
          "string.empty": "\"name\" is required",
          "string.min": "\"name\" length must be at least 3 characters long",
          "string.max": "\"name\" length must be at most 100 characters long",
          "any.required": "\"name\" is required",
        }),

      date: Joi.date()
        .iso()
        .required()
        .messages({
          "date.base": "\"date\" must be a valid date",
          "date.empty": "\"date\" is required",
          "any.required": "\"date\" is required",
        }),

      capacity: Joi.number()
        .integer()
        .min(5)
        .required()
        .messages({
          "number.base": "\"capacity\" must be a number",
          "number.integer": "\"capacity\" must be an integer",
          "number.min": "\"capacity\" must be greater than or equal to 5",
          "any.required": "\"capacity\" is required",
        }),

      registrationCount: Joi.number()
        .integer()
        .min(0)
        .max(100)
        .default(0)
        .messages({
          "number.base": "\"registrationCount\" must be a number",
          "number.integer": "\"registrationCount\" must be an integer",
          "number.min": "\"registrationCount\" cannot be negative",
          "number.max": "\"registrationCount\" must be less than or equal to ref:capacity",
        }),

      status: Joi.string()
        .valid("active", "cancelled", "completed")
        .default("active")
        .messages({
          "string.base": "\"status\" must be a string",
          "any.only": "\"status\" must be one of ['active', 'cancelled', 'completed']",
        }),

      category: Joi.string()
        .valid("general", "conference", "workshop", "meetup")
        .empty("")
        .default("general")
        .optional()
        .messages({
          "string.base": "\"category\" must be a string",
          "any.only": "\"category\" must be one of 'general', 'conference', 'workshop', or 'meetup'",
        }),
    }),
  },

  // GET /events
  getAll: {},

  // GET /events/:id
  getById: {
    params: Joi.object({
      id: Joi.string().required().messages({
        "string.base": "\"id\" must be a string",
        "string.empty": "\"id\" is required",
        "any.required": "\"id\" is required",
      }),
    }),
  },

  // PUT /events/:id
  update: {
    params: Joi.object({
      id: Joi.string().required().messages({
        "string.base": "\"id\" must be a string",
        "string.empty": "\"id\" is required",
        "any.required": "\"id\" is required",
      }),
    }),
    body: Joi.object({
      name: Joi.string().min(3).max(100).optional().messages({
        "string.base": "\"name\" must be a string",
        "string.empty": "\"name\" cannot be empty",
        "string.min": "\"name\" must be at least 3 characters",
        "string.max": "\"name\" must be at most 100 characters",
      }),

      date: Joi.string().isoDate().optional().messages({
        "string.base": "Date must be a string in ISO format",
        "string.empty": "Date cannot be empty",
        "string.isoDate": "Date must be in ISO format (YYYY-MM-DDTHH:mm:ss.sssZ)",
      }),

      capacity: Joi.number().integer().min(5).optional().messages({
        "number.base": "Capacity must be a number",
        "number.integer": "Capacity must be an integer",
        "number.min": "Capacity must be at least 5",
      }),

      registrationCount: Joi.number().integer().min(0).optional().messages({
        "number.base": "Registration count must be a number",
        "number.integer": "Registration count must be an integer",
        "number.min": "Registration count cannot be negative",
      }),

      status: Joi.string().valid("active", "inactive", "cancelled").optional().messages({
        "string.base": "Status must be a string",
        "string.empty": "Status cannot be empty",
        "any.only": "Status must be one of 'active', 'inactive', or 'cancelled'",
      }),

      category: Joi.string().valid("general", "conference", "workshop", "meetup").optional().messages({
        "string.base": "Category must be a string",
        "string.empty": "Category cannot be empty",
        "any.only": "Category must be one of 'general', 'conference', 'workshop', or 'meetup'",
      }),
    })
      // Optional but nice: require at least one field on update
      .min(1)
      .messages({ "object.min": "At least one field must be provided for update" }),
  },

  // DELETE /events/:id
  delete: {
    params: Joi.object({
      id: Joi.string().required().messages({
        "string.base": "ID must be a string",
        "string.empty": "ID is required",
        "any.required": "ID is required",
      }),
    }),
  },
};

/**
 * @openapi
 * components:
 *   schemas:
 *     Error:
 *       type: object
 *      required:
 *      - error
 *      - message
 *     properties:
 *       error:
 *         type: string
 *         description: A brief description of the error
 *       message:
 *         type: string
 *         description: A detailed message explaining the error
 *         example:
 *         error: "Bad Request"
 *         message: "Invalid request data"
 *       details:
 *         type: array
 *         items:
 *           type: object
 *           properties:
 *             field:
 *               type: string
 *               example: "name"
 *             issue:
 *               type: string
 *               example: "\"name\" is required"
 *             message:
 *               type: string
 *               example: "Invalid request data"
 *            description: An array of specific validation errors (if applicable)
 */