name: Deploy Documentation

on:
    name: Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: npm run generate-docs

      - name: Upload docs artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs